id: P009622
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:41:21.212536
source_metadata:
  id: bdr:W3CN6021
  title: སྐྱེས་ཆེན་དམ་པའི་རྟོགས་བརྗོད་ཐོར་བུ།
  author: ''
  volumes:
    ad2edfa8e56f438394cdac5b4aee6baa:
      image_group_id: I3CN6023
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
